/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header'
import { sanityClient,urlFor } from '../sanity'

export default function Home({ posts }) {

  //console.log(posts);

  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6">

        {posts.map(post => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className="cursor-pointer hover:scale-[1.02] ease-in-out duration-200 hover:shadow-2xl rounded">
              <img src={urlFor(post.mainImage).url()} alt="" className="h-100 w-140"/>
              <div className="flex items-center justify-between p-5 bg-white">
                <div>
                  <p className="text-lg font-bold">{post.title}</p>
                  <p className="text-gray-600">{post.description}</p>
                </div>
                <img src={urlFor(post.author.image).url()} alt="" className="h-10 w-10 rounded-full"/>
              </div> 
            </div>
          </Link>
        ))}
      </div>

      {/* <Footer /> */}

    </div>
  )
}


export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
      name,
      image
    },
    description,
    mainImage,
    slug,
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    }
  }

}
